## Label Encoding & Ordinal Encoding

In [4]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day26-ordinal-encoding/customer.csv')
df.sample(5)

,age,gender,review,education,purchased
0,30,Female,Average,School,No
37,94,Male,Average,PG,Yes
33,89,Female,Good,PG,Yes
10,98,Female,Good,UG,Yes
40,39,Male,Good,School,No


In [3]:
df = df.iloc[:,2:]
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [14]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
X_train

,review,education
15,Poor,UG
11,Good,UG
25,Good,School
22,Poor,PG
19,Poor,PG
29,Average,UG
47,Good,PG
10,Good,UG
45,Poor,PG
44,Average,UG


In [17]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)
X_train

array([[0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.]])

In [18]:
#Order of Yes and No is randomly decided by LabelEncoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
le.classes_

array(['No', 'Yes'], dtype=object)

In [19]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)
y_test

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0])

# One Hot Encoding

In [20]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day27-one-hot-encoding/cars.csv')
df.head()

,brand,km_driven,fuel,owner,selling_price
0,Maruti,145500,Diesel,First Owner,450000
1,Skoda,120000,Diesel,Second Owner,370000
2,Honda,140000,Petrol,Third Owner,158000
3,Hyundai,127000,Diesel,First Owner,225000
4,Maruti,120000,Petrol,First Owner,130000


## 1. OneHot Encoding using Pandas

In [21]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False


## 2. K-1 OneHotEncoding

In [23]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
#First columns removed automatically

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False


## 3. OneHotEncoding using Sci-Kit Learn

In [24]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(dtype=np.int32) 
# add drop='first' as paramter to account for Multicollinearity
#also adding sparse_output = False in paramters then we would directly get numpy arrays
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [35]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Jeep', 60000, 0, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 0, ..., 1, 0, 0],
       ['Isuzu', 121000, 0, ..., 0, 0, 0]], shape=(6502, 11), dtype=object)

## 4. OneHotEncoding with Top Categories

In [36]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [37]:
# uptill SKoda we will take seperate categories but after that we will club rest of them into "others" catgory

In [38]:
counts = df['brand'].value_counts()

In [40]:
df['brand'].nunique()
threshold = 100

In [41]:
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl,'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False


# Column Transformer

In [42]:
import pandas as pd
import numpy as np

In [44]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [46]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day28-column-transformer/covid_toy.csv')
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [47]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [48]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

### 1. AAM Zindagi

In [59]:
# Adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# Also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

In [50]:
# Ordinal Encoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

In [55]:
# OneHotEncoding -> Gender, City
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# Also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])


In [56]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','city','fever','cough']).values

# Also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [60]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# Also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [64]:
X_train_transformed = pd.DataFrame(X_train_transformed)
X_train_transformed.head()

,0,1,2,3,4,5,6
0,10.0,100.000000,1.0,0.0,0.0,0.0,0.0
1,34.0,100.830986,0.0,0.0,0.0,1.0,1.0
2,59.0,99.000000,0.0,1.0,0.0,0.0,1.0
3,64.0,101.000000,0.0,1.0,0.0,0.0,0.0
4,24.0,102.000000,0.0,0.0,0.0,0.0,1.0


### Mentos Zindagi

In [70]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [71]:
transformer.fit_transform(X_train)

array([[100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [100.83098592,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [100.83098592,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.    